configured_endpoints: 13
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/none-karimsamir897/thrive-mcp-9d57c577afb3e1ae3decc6a5db3a023d0abee5fee92059e612f446b33e6cb425.yml
openapi_spec_hash: db4d616cb096359d11f792c726c2eafb
config_hash: c5b9cb1f72c2cd1d6219ca2cfed18c92
